spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/aero
  docker:
    compose:
      file: ../docker-compose.yml
      lifecycle-management: start-only
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
